name: Lighthouse CI

on:
  push:

permissions:
  actions: read

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/client
    strategy:
      matrix:
        node-version: [22, latest]
    steps:
      - name: Download Client Build
        uses: actions/download-artifact@v4
        with:
          name: client-build_${{ matrix.node-version }}
          github-token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install lhci
        run: pnpm add -g @lhci/cli@0.14.x
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
