name: Build Storybook Documentation

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    defaults:
      run:
        working-directory: ./apps/docs
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build-storybook
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: docs-build_${{ matrix.node-version }}
          path: apps/docs/dist/
